### ISSUE TITLE
Debug drawing should ignore offset

### ISSUE THREAD

**Issue by catmanjan** [flixel-gdx/flixel-gdx-box2d#4]
I have a large polygon, and while debugging I noticed that the debug overlay line drawing was being moved along with the texture, this is incorrect, the debug drawing should remain where the physical bounds of the box is.

`B2FlxPolygon gutter = new B2FlxPolygon(0, 0, gutterVertices);
gutter.loadGraphic("pack:board");
gutter.offset = new FlxPoint(-2048 / 2, -1536 / 2);
gutter.setType(BodyType.StaticBody);
gutter.create();
add(gutter);`

**Comment by WingEraser** [comment]
Correct, can you make a PR? I'm currently busy with packing :). You can find them B2FlxShape drawSolidPolygon and drawSolidCircle.
